import type { Song } from "@/components/partials/MusicPlayer";

const rootDir = "/songs";

export const songs: Song[] = [
  {
    id: "01",
    name: "Asteri",
    artist: "Various Artists",
    img: rootDir + "/c-01.webp",
    src: rootDir + "/s-01.opus",
  },
  {
    id: "02",
    name: "Mou Leipeis",
    artist: "Various Artists",
    img: rootDir + "/c-02.webp",
    src: rootDir + "/s-02.opus",
  },
  {
    id: "03",
    name: "Lust",
    artist: "Various Artists",
    img: rootDir + "/c-03.webp",
    src: rootDir + "/s-03.opus",
  },
  {
    id: "04",
    name: "If You're A Star",
    artist: "Various Artists",
    img: rootDir + "/c-04.webp",
    src: rootDir + "/s-04.opus",
  },
  {
    id: "05",
    name: "Memories",
    artist: "Various Artists",
    img: rootDir + "/c-05.webp",
    src: rootDir + "/s-05.opus",
  },
  {
    id: "06",
    name: "Red River",
    artist: "Various Artists",
    img: rootDir + "/c-06.webp",
    src: rootDir + "/s-06.opus",
  },
  {
    id: "07",
    name: "Apology",
    artist: "Various Artists",
    img: rootDir + "/c-07.webp",
    src: rootDir + "/s-07.opus",
  },
  {
    id: "08",
    name: "Ola Ta Ksehnas",
    artist: "Various Artists",
    img: rootDir + "/c-08.webp",
    src: rootDir + "/s-08.opus",
  },
  {
    id: "09",
    name: "Breath",
    artist: "Various Artists",
    img: rootDir + "/c-09.webp",
    src: rootDir + "/s-09.opus",
  },
  {
    id: "10",
    name: "Mia Pista Apo Fosforo",
    artist: "Various Artists",
    img: rootDir + "/c-10.webp",
    src: rootDir + "/s-10.opus",
  },
  {
    id: "11",
    name: "Secret Love",
    artist: "Various Artists",
    img: rootDir + "/c-11.webp",
    src: rootDir + "/s-11.opus",
  },
  {
    id: "12",
    name: "Sen Gelmez Oldun",
    artist: "Various Artists",
    img: rootDir + "/c-12.webp",
    src: rootDir + "/s-12.opus",
  },
  {
    id: "13",
    name: "Santorini",
    artist: "Various Artists",
    img: rootDir + "/c-13.webp",
    src: rootDir + "/s-13.opus",
  },
  {
    id: "14",
    name: "DESTINO",
    artist: "Various Artists",
    img: rootDir + "/c-14.webp",
    src: rootDir + "/s-14.opus",
  },
  {
    id: "15",
    name: "Meltem",
    artist: "Various Artists",
    img: rootDir + "/c-15.webp",
    src: rootDir + "/s-15.opus",
  },
  {
    id: "16",
    name: "Always",
    artist: "Various Artists",
    img: rootDir + "/c-16.webp",
    src: rootDir + "/s-16.opus",
  },
  {
    id: "17",
    name: "Portitsa",
    artist: "Various Artists",
    img: rootDir + "/c-17.webp",
    src: rootDir + "/s-17.opus",
  },
  {
    id: "18",
    name: "Why - Remix",
    artist: "Various Artists",
    img: rootDir + "/c-18.webp",
    src: rootDir + "/s-18.opus",
  },
  {
    id: "19",
    name: "Sunset In Aegean",
    artist: "Various Artists",
    img: rootDir + "/c-19.webp",
    src: rootDir + "/s-19.opus",
  },
  {
    id: "20",
    name: "Lost Love",
    artist: "Various Artists",
    img: rootDir + "/c-20.webp",
    src: rootDir + "/s-20.opus",
  },
  {
    id: "21",
    name: "Don't Say Goodbye",
    artist: "Various Artists",
    img: rootDir + "/c-21.webp",
    src: rootDir + "/s-21.opus",
  },
  {
    id: "22",
    name: "Strings Pulses",
    artist: "Various Artists",
    img: rootDir + "/c-22.webp",
    src: rootDir + "/s-22.opus",
  },
];
